version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
<<<<<<< HEAD
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
=======
>>>>>>> ea4a09d2c20a4d9611a5515123ba27b2c23e7a21
